fix for bug 2911: check log file name

diff --git a/scripts/vyatta-show-log-file b/scripts/vyatta-show-log-file
--- a/scripts/vyatta-show-log-file
+++ b/scripts/vyatta-show-log-file
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-if [ -f /var/log/user/$1 ]; then
+if [[ "$1" == */* ]]; then
+  echo "Invalid log file name"
+  exit 1
+fi
+
+if [ -f "/var/log/user/$1" ]; then
   cat /var/log/user/$1
 else
   echo "No such log file"
